######################################################################
# Automatically generated by qmake (3.0) ?? 3? 13 17:46:00 2015
######################################################################

QT += network
TEMPLATE = app
TARGET = qt-redis-qt-redis
INCLUDEPATH += .

# Input
HEADERS += \
    qRedis.h \
    qReader.h \
    qReadisTest.h
SOURCES += main.cpp \
    qRedis.cpp \
    qReader.cpp \
    qReadisTest.cpp
